openapi: 3.0.0
info:
  title: Marketplace Admin Swagger
  description: Swagger
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Admin Dashboard
  - name: Admin Dashboard > Auth
  - name: Admin Dashboard > Account Office
  - name: Admin Dashboard > Company
  - name: AO Dashboard
paths:
  /api/admin/login:
    post:
      tags:
        - Admin Dashboard > Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: superadmin@admin.com
                password: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/refresh:
    post:
      tags:
        - Admin Dashboard > Auth
      summary: Refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refresh_token: >-
                  def50200bfcb5b34199e56a98562af8af9251646fa6535e60bf8949543f4695553e1913754f79965ab14852328dcd8146505e40f45735ac25a582685edcb1dca493daf4a297d407c48efc44ec9587a39f615aa613ebd1b075f9deb81ae4445d46c38ccaa9a2fe6d35eeb2540f33b727db6317cab927fc217e0823bf8187034240939bfa90ac404deb0ae38e7de3b21b80c9741d40ab0046e1615c29b492e6bdd6acf5a04b8ad9dd9462cc5fd1ce32e87238a770fb4c63b3d5ad1c1cd88c3216973ab69b23704e56969408572ad4075dd5df0623f68dc9ac7a4cefbc9993f8282f2190307bb4c00e69ac8da54f21d2913b053684d1489f51d25f842773cab8a46760ee3a020fd53f33fab7d1db96b84d18b3f7311510096324973ffcd07e519cfd4ad8a0786e307a49591ab6c6483bcafd3fd9849c75302b1026a1f56c862fa9c6811ae00cec22859f59728cce482c1bab9dcf7f4f57a3cb52819c80be9bf0c7d1147af38
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/account-office:
    get:
      tags:
        - Admin Dashboard > Account Office
      summary: List Accounting Office
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: perPage
          in: query
          schema:
            type: integer
          example: '20'
        - name: name
          in: query
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Admin Dashboard > Account Office
      summary: Create Account Office
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: office second
                email: office_second@mail.com
                short_name: office
                tax_id: 12356
                regon: 13456
                bdo: 45677
                pkd: pkd
                krs: krs
                www: www
                is_tax_adviser: 1
                is_current_review: 0
                nr_mf: abc
                phone_number: '123412'
                addresses:
                  country: Nepal
                  city: Kathmandu
                  zip: '9800'
                  post: p1
                  street: street 1
                  district: district 1
                  county: county 1
                  house_number: h 123
                  no_of_premises: pr 4
                  voivodeship: voivo 2
                user_name: test office
                user_email: secondOffice@gmail.com
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/accounting-office/{slug}/admin:
    put:
      tags:
        - Admin Dashboard > Account Office
      summary: Change Accounting Office Admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_name: test rename 2
                user_email: testOffice2@gmail.com
      security:
        - bearerAuth: []
      parameters:
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: office-second
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/company:
    get:
      tags:
        - Admin Dashboard > Company
      summary: List Companies
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: sort_key
          in: query
          schema:
            type: string
          example: name
        - name: sort_order
          in: query
          schema:
            type: string
          example: desc
        - name: limit
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
          description: 'values: active, inactive'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Admin Dashboard > Company
      summary: Create Company
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: second comp
                short_name: def
                email: second@mail.com
                phone: +91 2142802
                addresses:
                  country: Poland
                  city: Warswa
                  zip: '9800'
                  post: p1
                  street: street 1
                  district: district 1
                  county: county 1
                  house_number: h 123
                  no_of_premises: pr 4
                  voivodeship: voivo 2
                user_name: second user
                user_email: seconduser@mail.com
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/company/{slug}:
    put:
      tags:
        - Admin Dashboard > Company
      summary: Update Company
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: second comp updated
                short_name: def
                tax_id: 456
                regon: regon
                bdo: bdo
                pkd: pkd
                krs: krs
                ceidg: null
                phone_number: phone
                is_small_company: 0
                email: seconds@mail.com
                created_at: '2023-07-19'
                addresses:
                  country: Polands
                  street: street 1
                  city: Warswas
                  zip: 9800s
                  post: p1s
                  house_number: h 123s
                  number_of_premises: null
                  district: district 1s
                  county: county 1s
                  voivodeship: voivo 2s
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: second-comp
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/company/{slug}/change-active:
    patch:
      tags:
        - Admin Dashboard > Company
      summary: Change Company Status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                value: 0
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: company-4th
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/company/{slug}:
    get:
      tags:
        - Admin Dashboard > Company
      summary: Company Detail
      security:
        - noauthAuth: []
      parameters:
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: company-two-1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/company/{company_id}/admin:
    put:
      tags:
        - Admin Dashboard > Company
      summary: Update company admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Someone
                email: someuser@mail.com
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: company_id
          in: path
          schema:
            type: integer
          required: true
          example: '11'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
